### Get chat history
GET http://localhost:3000/chat

### Get previous 20 messages
GET http://localhost:3000/chat?timestamp=2025-01-06T16:45:09.086Z

### Send new prompt
### To avoid errors while testing, dont forget to change timestamp
POST http://localhost:3000/chat
Content-Type: application/json

{
    "message": "Say this is a test",
    "timestamp": "2024-13-20T18:48:57.815Z",
    "isAI": false
}